apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: owl-app
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: owl-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    any: true
