server:
  port: ${PORT:9090}

spring:
  ai:
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        collection-name: ${QDRANT_COLLECTION:owl_kb}
        distance: COSINE
        initialize-schema: true
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        options:
          model: ${OLLAMA_EMBED_MODEL:nomic-embed-text}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

