name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    name: Build & Test (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['.', 'services/retrieval-service', 'services/safety-service', 'services/model-proxy']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Test ${{ matrix.module }}
        run: mvn -q -B -f ${{ matrix.module }}/pom.xml test

  docker-build-push:
    name: Docker Build & Push
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push owl-app
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-owl-app:${{ github.sha }}
            ghcr.io/${{ github.repository }}-owl-app:latest
      - name: Build & Push retrieval-service
        uses: docker/build-push-action@v5
        with:
          context: services/retrieval-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-retrieval-service:${{ github.sha }}
            ghcr.io/${{ github.repository }}-retrieval-service:latest
      - name: Build & Push safety-service
        uses: docker/build-push-action@v5
        with:
          context: services/safety-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-safety-service:${{ github.sha }}
            ghcr.io/${{ github.repository }}-safety-service:latest
      - name: Build & Push model-proxy
        uses: docker/build-push-action@v5
        with:
          context: services/model-proxy
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-model-proxy:${{ github.sha }}
            ghcr.io/${{ github.repository }}-model-proxy:latest

  helm-package:
    name: Helm Package
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package charts
        run: |
          mkdir -p helm-packages
          for chart in deploy/helm/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $chart";
              helm package "$chart" -d helm-packages;
            fi
          done
      - uses: actions/upload-artifact@v4
        with:
          name: helm-charts
          path: helm-packages

